package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.KotlinScriptFileBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.kotlinFile
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'GitTags'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("GitTags")) {
    check(maxRunningBuilds == 0) {
        "Unexpected option value: maxRunningBuilds = $maxRunningBuilds"
    }
    maxRunningBuilds = 1

    vcs {

        check(checkoutMode == CheckoutMode.AUTO) {
            "Unexpected option value: checkoutMode = $checkoutMode"
        }
        checkoutMode = CheckoutMode.ON_AGENT
    }

    expectSteps {
        script {
            name = "Create Tag"
            scriptContent = """
                echo "Team city"
                curl --location 'https://api.github.com/repos/thusitha458/teamcity-test/git/refs/tags' \
                                --header 'X-GitHub-Api-Version: 2022-11-28' \
                                --header 'Authorization: Bearer %env.GITHUB_TOKEN%'
            """.trimIndent()
        }
        kotlinFile {
            name = "Kotlin FTW"
            path = ".teamcity/myscript.main.kts"
            arguments = "%env.GITHUB_TOKEN%"
        }
    }
    steps {
        update<KotlinScriptFileBuildStep>(1) {
            name = "Calculate version"
            clearConditions()
        }
    }
}
